server:
  port: 8765
spring:
  application:
    name: Service-Consumer
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
eureka:
  client:
    service-url:
      defaultZone: http://10.10.11.101:8761/eureka/
feign:
  hystrix:
    enabled: true
