server:
  port: 8765
spring:
  application:
    name: Service-Consumer
 servlet:
    multipart:
      max-file-size: 10485760
      max-request-size: 10485760
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
